---
namespace: kubevirt
name: core
version: "1.2.2"
readme: README.md
authors:
  - KubeVirt Project (kubevirt.io)
dependencies:
  kubernetes.core: '>=3.0.1'
description: Lean Ansible bindings for KubeVirt
license_file: LICENSE
tags:
  - api
  - k8s
  - kubernetes
  - kubevirt
  - virtualization
  - cloud
  - infrastructure
repository: https://github.com/kubevirt/kubevirt.core
documentation: https://kubevirt.github.io/kubevirt.core
homepage: https://kubevirt.io
issues: https://github.com/kubevirt/kubevirt.core/issues
build_ignore:
  - .ansible-lint
  - .git
  - .gitignore
  - .github
  - .yamllint
  - bin
  - changelogs
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - examples
  - hack
  - Makefile
  - OWNERS
  - REVIEW_CHECKLIST.md
  - '*.tar.gz'
  - '*.zip'
  - docs/_gh_include
  - docs/conf.py
  - docs/CONTRIBUTING.md
  - docs/roles.rst.template
  - docs/requirements.yml
