---
- name: Playbook terminating a virtual machine
  hosts: localhost
  tasks:
    - name: Delete VM
      kubevirt.core.kubevirt_vm:
        name: testvm
        namespace: default
        state: absent
        wait: true
