- name: Playbook instantiating a virtual machine
  hosts: localhost
  tasks:
    - name: Create VM
      kubevirt.core.kubevirt_vm:
        state: present
        name: testvm
        namespace: default
        running: no
