---
- name: Playbook terminating a virtual machine with data volume
  hosts: localhost
  tasks:
    - name: Delete VM
      kubevirt.core.kubevirt_vm:
        name: testvm-with-dv
        namespace: default
        state: absent
        wait: true
